class board(object):
    def __init__(self,board_file):
        self.board = self.__create_board(board_file)
    def __create_board(self,board_file):
        #create the matrix data struct for the board
        board = []
        #iterate over each line of the matrix
        for line in board_file:
            line = line.strip()
            
            #error check the board matches with the suduko rules
            #9 lines in total 9x9 grid / 3x3 boxes
            #line should not be shorter/longer than 9 char
            #char should only be int
            if len(line) != 9:
                board = []
                print("Error with the amount of characters generated by the board")
            #creating a list for the board
            board.append([])
            #iterate over the char 
            for c in line:
                #raise an error if char != int
                if not c.isdigit():
                    print("valid characters in suduko are 1-9")
                board[-1].append(int(c)) 
            # error checking for number of lines on board
            if len(board) != 9:
                print('Error with the amount of lines on the board')
            return board

#class sudukoGame(object):                
print(board)